### ISSUE TITLE
Messaging Flows and Messaging Delivery Flows differ

### ISSUE THREAD

**Issue by cantlep** [darold/sendmailanalyzer#51]
Hi Gilles,

I notice that in my setup. In Global Statistics -> Messaging

In Messaging Flows, both the Incoming and outgoing message numbers are displayed. However, in the messaging flows section, only the Internal -> External (which does correctly correspond with the Outgoing Message Flow) is displayed. The External -> Internal (which should correspond with Incoming Message flow) remains at 0.

![message_flows](https://user-images.githubusercontent.com/3270673/30453603-4cbd0ed8-9991-11e7-9b08-45ea00a2b44f.png)

I think these should correspond with each other.

Thanks

**Comment by jules38** [comment]
Have you tried latest development code or is it related to v9.2?

**Comment by cantlep** [comment]
Hi, This is v9.2

**Comment by darold** [comment]
Paul, please send a log and your sendmailanalyzer.conf to my private email, without them I will not be able to understand and find what's going wrong.

**Comment by darold** [comment]
Commit 76cda01 fixes the differences in mail direction in sa_cache. I'll send you the configuration file that you should use to have the right delivery flow. You will need to rebuild the cache to have the right reports on older data.

**Comment by cantlep** [comment]
Hi @darold Looks great now - Thanks again for your continued work on this. It's much appreciated.

**Comment by cantlep** [comment]
Hi @darold Apologies, whilst the i/c o/g flows are fixed, the issue with the messaging flows remains. See screenshots for a particular domain in a 1 hour window (just to show a bit less traffic)

Delivery_flows looks good. 4 emails i/c

![delivery_flows](https://user-images.githubusercontent.com/3270673/31379204-8e8c6cb4-ada5-11e7-8c09-0f5aabe3e75d.png)

Messaging Flows is incorrect though. There were no outbound emails

![messsaging_flows](https://user-images.githubusercontent.com/3270673/31379313-c69b3022-ada5-11e7-937c-c798cad178de.png)

Senders / Recipients in the Top stats section all look good. It's just the Messaging Flows that are now not correct.

Sorry :-S

**Comment by Steffan72** [comment]
I have the same problem as Cantlep.
The updated code doesnt fix it for me.

**Comment by darold** [comment]
I'm not able to reproduce this issue reported by cantlep and you. Can you send to my private email the log file and your configuration file? Also point me the exact hour where the problem is reproducible.

**Comment by darold** [comment]
The last two commit 88d501e and 4eb40a9 could solve this issue too, please check latest development code and let me know.

**Comment by darold** [comment]
The @Steffan72 issue can be solved by adding `dovecot,local`, and all the internal domain name handled by this MTA, to the LOCAL_DOMAIN directive. @cantlep if you can send me the log file part that for you generate the problem and was expected, it will help me to explain what should be done in configuration file or to find the bug.
